CREATE TABLE LOGPAS
(
  ID_lOGPAS INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  LOGIN_VALUE VARCHAR(50) NOT NULL ,
  PASSWORD_VALUE VARCHAR(50) NOT NULL,
  USER_TYPE VARCHAR(50) NOT NULL
);

CREATE TABLE CLIENTS (
  ID_CLIENT INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  ID_LOGPAS INT NOT NULL,
  FIRSTNAME_CLIENT VARCHAR(50) NOT NULL,
  LASTNAME_CLIENT VARCHAR(50) NOT NULL,
  MIDDLENAME_CLIENT VARCHAR(50) NOT NULL,
  AGE_CLIENT INT NOT NULL,
  GENDER_CLIENT VARCHAR(10) NOT NULL,
  PHONENAME_CLIENT VARCHAR(20) NOT NULL,
  FOREIGN KEY(ID_LOGPAS) REFERENCES LOGPAS(ID_lOGPAS)
);

Select * from clients;

CREATE TABLE EMPLOYEES (
    ID_EMPLOYEE INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	ID_LOGPAS INT NOT NULL,
    FIRSTNAME_EMPLOYEE VARCHAR(50) NOT NULL,
    LASTNAME_EMPLOYEE VARCHAR(50) NOT NULL,
    PHONENAME_EMPLOYEE VARCHAR(20) NOT NULL,
	SALARY_EMPLOYEE INT NOT NULL,
	FOREIGN KEY(ID_LOGPAS) REFERENCES LOGPAS(ID_lOGPAS)
);

CREATE TABLE ABONEMENTS(
	ID_ABONEMENT INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PRICE_ABONEMENT MONEY NOT NULL,
	AMOUNT_OF_VISITS INT NOT NULL,
	IMG_ABONEMENT VARBINARY NOT NULL
);

CREATE TABLE ABONEMENTS (
    ID_ABONEMENT INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	ID_SHEDULE INT NOT NULL,
    PRICE_ABONEMENT MONEY NOT NULL,
    AMOUNT_OF_VISITS INT NOT NULL,
    IMG_ABONEMENT VARBINARY(MAX) NOT NULL,
    TYPE_OF_ABONEMENT VARCHAR(255),
    TYPE_OF_EXERCISE VARCHAR(255),
    ADDITIONAL_SERVICE VARCHAR(255),
	FOREIGN KEY(ID_SHEDULE) REFERENCES SHEDULE_TABLE(ID_SHEDULE)
);

DROP TABLE SALEOFABONEMENTS;
DROP TABLE ABONEMENT_REQUEST;
DROP TABLE ABONEMENTS;
DROP TABLE SHEDULE_TABLE;

CREATE TABLE SALEOFABONEMENTS(
	ID_SALE INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	ID_CLIENT INT NOT NULL,
	ID_ABONEMENT INT NOT NULL,
	DATA_BEGIN DATE,
	DATA_END DATE,
	FOREIGN KEY (ID_CLIENT) REFERENCES CLIENTS(ID_CLIENT),
    FOREIGN KEY (ID_ABONEMENT) REFERENCES ABONEMENTS(ID_ABONEMENT)
);

CREATE TABLE ABONEMENT_REQUEST (
	ID_REQUEST INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	ID_CLIENT INT NOT NULL,
	ID_ABONEMENT INT NOT NULL,
	TYPE_OF_TRAINING VARCHAR(50) NOT NULL,
	TYPE_OF_SERVICE VARCHAR(50) NOT NULL,
	DATA_REQUEST DATE,
	FOREIGN KEY (ID_CLIENT) REFERENCES CLIENTS(ID_CLIENT),
	FOREIGN KEY (ID_ABONEMENT) REFERENCES ABONEMENTS(ID_ABONEMENT)
);

CREATE TABLE SHEDULE_TABLE(
    ID_SHEDULE INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    MONDAY VARCHAR(255) NOT NULL,
    TUESDAY VARCHAR(255) NOT NULL,
    WEDNRSDAY VARCHAR(255) NOT NULL,
    THURSDAY VARCHAR(255) NOT NULL,
    FRIDAY VARCHAR(255) NOT NULL,
    SATURDAY VARCHAR(255) NOT NULL,
    SUNDAY VARCHAR(255) NOT NULL,
);

INSERT INTO SHEDULE_TABLE (MONDAY, TUESDAY, WEDNRSDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY)
VALUES
('03:00 PM - 05:00 PM', '04:00 PM - 07:00 PM', '01:00 PM - 02:00 PM', '02:30 PM - 05:30 PM', '07:00 PM - 10:00 PM', '08:00 PM - 12:00 AM', '־עהûץ');

DROP TABLE LOGPAS;
DROP TABLE CLIENTS;
DROP TABLE EMPLOYEES;
DROP TABLE ABONEMENTS;
DROP TABLE SALEOFABONEMENTS;
DROP TABLE ABONEMENT_REQUEST;